name: WorldRegen
main: com.kafeijao.worldregen.WorldRegen
version: 0.0.1

depend: [WorldEdit, WorldGuard, Multiverse-Core]

description: My first testing plugin, probably multipurpose n stuff.
author: Kafeijao
website: kafeijao.com

commands:
    rain:
        description: Makes RAIN :D
        usage: /rain
        permission: WorldRegen.rain
        permission-message: You don't have WorldRegen.rain

    norain:
        description: Makes SUN :D
        usage: /norain
        permission: WorldRegen.rain
        permission-message: You don't have WorldRegen.norain
        
    lightning:
        description: LIGHTNING the shit out of someone
        usage: /lightning [player]
        aliases: l
        permission: WorldRegen.lightning
        permission-message: You don't have WorldRegen.lightning
        
    importXML:
        description: Import backups of Plots.
        usage: /importXML [regionName] [yyyy-mm-dd]
        permission: WorldRegen.importXML
        permission-message: You don't have permission to execute the command.
        
permissions:
    WorldRegen.rain:
        description: ALLOW MAKE RAIN
        default: true
        
    WorldRegen.norain:
        description: ALLOW UNMAKE RAIN
        default: true
        
    WorldRegen.lightning:
        description: ALLOW LIGHTNING THE SHIT OUT OF SOMEONE
        default: true
    
    WorldRegen.importXML:
        description: Allow import backups of Plots
        default: false